/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsDownloadAsset } from "../../funcs/assetsDownloadAsset.js";
import { DownloadAssetRequest$zodSchema } from "../../models/downloadassetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DownloadAssetRequest$zodSchema,
};

export const tool$assetsDownloadAsset: ToolDefinition<typeof args> = {
  name: "download-asset",
  description: `Generates a download link for a specific asset (image)`,
  scopes: ["admin"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsDownloadAsset(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
