/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsGetResourceByAssetId } from "../../funcs/assetsGetResourceByAssetId.js";
import { GetResourceByAssetIdRequest$zodSchema } from "../../models/getresourcebyassetidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetResourceByAssetIdRequest$zodSchema,
};

export const tool$assetsGetResourceByAssetId: ToolDefinition<typeof args> = {
  name: "get-asset-details",
  description: `Get resource by asset ID

Returns the details of a single resource specified by its asset ID.`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsGetResourceByAssetId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
