/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsDownloadBackupAsset } from "../../funcs/assetsDownloadBackupAsset.js";
import { DownloadBackupAssetRequest$zodSchema } from "../../models/downloadbackupassetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DownloadBackupAssetRequest$zodSchema,
};

export const tool$assetsDownloadBackupAsset: ToolDefinition<typeof args> = {
  name: "download-asset-backup",
  description: `Download a backup copy of an asset`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsDownloadBackupAsset(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
