/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsListImages } from "../../funcs/assetsListImages.js";
import { ListImagesRequest$zodSchema } from "../../models/listimagesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListImagesRequest$zodSchema.optional(),
};

export const tool$assetsListImages: ToolDefinition<typeof args> = {
  name: "list-images",
  description: `Get image assets

Retrieves a list of image assets. Results can be filtered by various criteria like tags, moderation status, prefix, or specific public IDs.
`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsListImages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
