/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsRenameAsset } from "../../funcs/assetsRenameAsset.js";
import { RenameAssetRequest$zodSchema } from "../../models/renameassetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RenameAssetRequest$zodSchema,
};

export const tool$assetsRenameAsset: ToolDefinition<typeof args> = {
  name: "asset-public_id-rename",
  description:
    `Updates an existing asset's identifier and optionally other metadata in your Cloudinary account`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsRenameAsset(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
