/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsListResourceTags } from "../../funcs/assetsListResourceTags.js";
import { ListResourceTagsRequest$zodSchema } from "../../models/listresourcetagsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListResourceTagsRequest$zodSchema,
};

export const tool$assetsListResourceTags: ToolDefinition<typeof args> = {
  name: "list-tags",
  description:
    `Retrieves a list of tags currently applied to assets in your Cloudinary account

Retrieves a comprehensive list of all tags that exist in your product environment for assets of the specified type.

[Cloudinary Admin API documentation](https://cloudinary.com/documentation/admin_api)
`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetsListResourceTags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
