/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { foldersSearchFolders } from "../../funcs/foldersSearchFolders.js";
import { SearchFoldersRequest$zodSchema } from "../../models/searchfoldersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SearchFoldersRequest$zodSchema.optional(),
};

export const tool$foldersSearchFolders: ToolDefinition<typeof args> = {
  name: "search-folders",
  description: `Searches for folders whose attributes match a given expression

Lists the folders that match the specified search expression. Limited to 2000 results. If no parameters are passed, returns the 50 most recently created folders in descending order of creation time.
`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await foldersSearchFolders(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
