/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { foldersDestroyFolder } from "../../funcs/foldersDestroyFolder.js";
import { DestroyFolderRequest$zodSchema } from "../../models/destroyfolderop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DestroyFolderRequest$zodSchema,
};

export const tool$foldersDestroyFolder: ToolDefinition<typeof args> = {
  name: "delete-folder",
  description: `Deletes an existing folder from your media library

Deletes a folder and all assets within it.`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await foldersDestroyFolder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
