/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { foldersCreateFolder } from "../../funcs/foldersCreateFolder.js";
import { CreateFolderRequest$zodSchema } from "../../models/createfolderop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateFolderRequest$zodSchema,
};

export const tool$foldersCreateFolder: ToolDefinition<typeof args> = {
  name: "create-folder",
  description: `Creates a new empty folder in your Cloudinary media library

Creates a new folder at the specified path`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await foldersCreateFolder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
