/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { foldersUpdateFolder } from "../../funcs/foldersUpdateFolder.js";
import { UpdateFolderRequest$zodSchema } from "../../models/updatefolderop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFolderRequest$zodSchema,
};

export const tool$foldersUpdateFolder: ToolDefinition<typeof args> = {
  name: "move-folder",
  description:
    `Renames or moves an entire folder (along with all assets it contains) to a

Updates a folder's properties.`,
  scopes: ["librarian"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await foldersUpdateFolder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
