/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageGetUsage } from "../../funcs/usageGetUsage.js";
import { GetUsageRequest$zodSchema } from "../../models/getusageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUsageRequest$zodSchema.optional(),
};

export const tool$usageGetUsage: ToolDefinition<typeof args> = {
  name: "get-usage-details",
  description: `Retrieves comprehensive usage metrics and account statistics

A report on the status of product environment usage, including storage, credits, bandwidth, requests, number of resources, and add-on usage.`,
  scopes: ["admin"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usageGetUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
