/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeFormQuery, encodeSimple, queryJoin } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  ListResourcesByModerationKindAndStatusRequest,
  ListResourcesByModerationKindAndStatusRequest$zodSchema,
  ListResourcesByModerationKindAndStatusResponse,
  ListResourcesByModerationKindAndStatusResponse$zodSchema,
} from "../models/listresourcesbymoderationkindandstatusop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get resources by moderation kind and status
 *
 * @remarks
 * Retrieves resources matching specific moderation kind and status.
 */
export function assetsListResourcesByModerationKindAndStatus(
  client$: SDKCore,
  request: ListResourcesByModerationKindAndStatusRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    ListResourcesByModerationKindAndStatusResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  request: ListResourcesByModerationKindAndStatusRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      ListResourcesByModerationKindAndStatusResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) =>
      ListResourcesByModerationKindAndStatusRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    cloud_name: encodeSimple("cloud_name", client$._options.cloud_name, {
      explode: false,
      charEncoding: "percent",
    }),
    moderation_kind: encodeSimple("moderation_kind", payload$.moderation_kind, {
      explode: false,
      charEncoding: "percent",
    }),
    moderation_status: encodeSimple(
      "moderation_status",
      payload$.moderation_status,
      { explode: false, charEncoding: "percent" },
    ),
    resource_type: encodeSimple("resource_type", payload$.resource_type, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc(
    "/v1_1/{cloud_name}/resources/{resource_type}/moderations/{moderation_kind}/{moderation_status}",
  )(
    pathParams$,
  );
  const query$ = queryJoin(
    encodeFormQuery({
      "fields": payload$.fields,
    }, { explode: false }),
    encodeFormQuery({
      "direction": payload$.direction,
      "max_results": payload$.max_results,
      "next_cursor": payload$.next_cursor,
    }),
  );

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "listResourcesByModerationKindAndStatus",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    ListResourcesByModerationKindAndStatusResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, ListResourcesByModerationKindAndStatusResponse$zodSchema, {
      key: "list_response",
    }),
    M.json(
      [400, 401],
      ListResourcesByModerationKindAndStatusResponse$zodSchema,
      { key: "api_error" },
    ),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
