/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  DownloadBackupAssetRequest,
  DownloadBackupAssetRequest$zodSchema,
  DownloadBackupAssetResponse,
  DownloadBackupAssetResponse$zodSchema,
} from "../models/downloadbackupassetop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

export enum DownloadBackupAssetAcceptEnum {
  applicationJsonAccept = "application/json",
  textPlainAccept = "text/plain",
  applicationOctetStreamAccept = "application/octet-stream",
  videoWildcardAccept = "video/*",
  imageWildcardAccept = "image/*",
}

/**
 * Download a backup copy of an asset
 */
export function assetsDownloadBackupAsset(
  client$: SDKCore,
  request: DownloadBackupAssetRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    DownloadBackupAssetResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  request: DownloadBackupAssetRequest,
  options?: RequestOptions & {
    acceptHeaderOverride?: DownloadBackupAssetAcceptEnum;
  },
): Promise<
  [
    Result<
      DownloadBackupAssetResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => DownloadBackupAssetRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    cloud_name: encodeSimple("cloud_name", client$._options.cloud_name, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/v1_1/{cloud_name}/download_backup")(
    pathParams$,
  );
  const query$ = encodeFormQuery({
    "api_key": payload$.api_key,
    "asset_id": payload$.asset_id,
    "signature": payload$.signature,
    "timestamp": payload$.timestamp,
    "version_id": payload$.version_id,
  });

  const headers$ = new Headers(compactMap({
    Accept: options?.acceptHeaderOverride
      || "application/json;q=1, text/plain;q=0.8, application/octet-stream;q=0.6, video/*;q=0.4, image/*;q=0",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "downloadBackupAsset",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    DownloadBackupAssetResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.bytes(200, DownloadBackupAssetResponse$zodSchema, {
      key: "200_application/octet-stream_bytes",
    }),
    M.bytes(200, DownloadBackupAssetResponse$zodSchema, {
      ctype: "text/plain",
      key: "200_text/plain_bytes",
    }),
    M.bytes(200, DownloadBackupAssetResponse$zodSchema, {
      ctype: "image/*",
      key: "200_image/*_bytes",
    }),
    M.bytes(200, DownloadBackupAssetResponse$zodSchema, {
      ctype: "video/*",
      key: "200_video/*_bytes",
    }),
    M.json(400, DownloadBackupAssetResponse$zodSchema, {
      key: "400_application/json_object",
    }),
    M.json(401, DownloadBackupAssetResponse$zodSchema, {
      key: "401_application/json_object",
    }),
    M.json(404, DownloadBackupAssetResponse$zodSchema, {
      key: "404_application/json_object",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
