/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export const mcpScopes = [
  "admin",
  "builder",
  "librarian",
] as const;

export type MCPScope = (typeof mcpScopes)[number];
