/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiErrorError = { message: string };

export const ApiErrorError$zodSchema: z.ZodType<
  ApiErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export type ApiError = { error: ApiErrorError };

export const ApiError$zodSchema: z.ZodType<ApiError, z.ZodTypeDef, unknown> = z
  .object({
    error: z.lazy(() => ApiErrorError$zodSchema),
  });
