/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of resources to include in the archive. "image" for images, "video" for videos, "raw" for non-media files, or "all" for mixed types.
 */
export const ArchiveResourceType$zodSchema = z.enum([
  "image",
  "video",
  "raw",
  "all",
]).describe(
  "The type of resources to include in the archive. \"image\" for images, \"video\" for videos, \"raw\" for non-media files, or \"all\" for mixed types.",
);

export type ArchiveResourceType = z.infer<typeof ArchiveResourceType$zodSchema>;
