/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The storage type of resources to include in the archive.
 */
export const ArchiveStorageType$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "fetch",
]).describe("The storage type of resources to include in the archive.");

export type ArchiveStorageType = z.infer<typeof ArchiveStorageType$zodSchema>;
