/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The code indicating the result of the operation.
 */
export const Code$zodSchema = z.enum([
  "rejected_ids",
  "invalid_ids",
  "internal_error_ids",
  "non_existing_ids",
  "invalid_relate_to_self_id",
  "already_exists_ids",
  "relation_does_not_exist_ids",
  "success_ids",
]).describe("The code indicating the result of the operation.");

export type Code = z.infer<typeof Code$zodSchema>;

export type AssetRelationInfo = {
  message?: string | undefined;
  code?: Code | undefined;
  asset?: string | undefined;
  status?: number | undefined;
};

export const AssetRelationInfo$zodSchema: z.ZodType<
  AssetRelationInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset: z.string().optional(),
  code: Code$zodSchema.optional(),
  message: z.string().optional(),
  status: z.number().int().optional(),
});
