/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AssetRelationInfo,
  AssetRelationInfo$zodSchema,
} from "./assetrelationinfo.js";

export type AssetRelationsDeleteResponse = {
  failed?: Array<AssetRelationInfo> | undefined;
  success?: Array<AssetRelationInfo> | undefined;
};

export const AssetRelationsDeleteResponse$zodSchema: z.ZodType<
  AssetRelationsDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  failed: z.array(AssetRelationInfo$zodSchema).optional(),
  success: z.array(AssetRelationInfo$zodSchema).optional(),
});
