/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type CreateFolderGlobals = { cloud_name?: string | undefined };

export const CreateFolderGlobals$zodSchema: z.ZodType<
  CreateFolderGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateFolderRequest = { folder: string };

export const CreateFolderRequest$zodSchema: z.ZodType<
  CreateFolderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder: z.string(),
});

/**
 * Folder created successfully
 */
export type CreateFolderResponseBody = {
  success?: boolean | undefined;
  path?: string | undefined;
  name?: string | undefined;
};

export const CreateFolderResponseBody$zodSchema: z.ZodType<
  CreateFolderResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  path: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Folder created successfully");

export type CreateFolderResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CreateFolderResponseBody | undefined;
  api_error?: ApiError | undefined;
};

export const CreateFolderResponse$zodSchema: z.ZodType<
  CreateFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  object: z.lazy(() => CreateFolderResponseBody$zodSchema).optional(),
});
