/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AssetRelationsDeleteResponse,
  AssetRelationsDeleteResponse$zodSchema,
} from "./assetrelationsdeleteresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import { StorageType, StorageType$zodSchema } from "./storagetype.js";

export type DeleteAssetRelationsByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteAssetRelationsByPublicIdGlobals$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteAssetRelationsByPublicIdRequestBody = {
  assets_to_unrelate: Array<string>;
};

export const DeleteAssetRelationsByPublicIdRequestBody$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  assets_to_unrelate: z.array(z.string()),
});

export type DeleteAssetRelationsByPublicIdRequest = {
  resource_type: ResourceType;
  type: StorageType;
  public_id: string;
  RequestBody: DeleteAssetRelationsByPublicIdRequestBody;
};

export const DeleteAssetRelationsByPublicIdRequest$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() =>
    DeleteAssetRelationsByPublicIdRequestBody$zodSchema
  ),
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema,
  type: StorageType$zodSchema,
});

export type DeleteAssetRelationsByPublicIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  asset_relations_delete_response?: AssetRelationsDeleteResponse | undefined;
  api_error?: ApiError | undefined;
};

export const DeleteAssetRelationsByPublicIdResponse$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  asset_relations_delete_response: AssetRelationsDeleteResponse$zodSchema
    .optional(),
});
