/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DerivedDestroyResponse,
  DerivedDestroyResponse$zodSchema,
} from "./deriveddestroyresponse.js";

export type DerivedDestroyGlobals = { cloud_name?: string | undefined };

export const DerivedDestroyGlobals$zodSchema: z.ZodType<
  DerivedDestroyGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DerivedDestroyResponseResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  DerivedDestroyResponse?: DerivedDestroyResponse | undefined;
  api_error?: ApiError | undefined;
};

export const DerivedDestroyResponseResponse$zodSchema: z.ZodType<
  DerivedDestroyResponseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  DerivedDestroyResponse: DerivedDestroyResponse$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
});
