/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request parameters for deleting derived resources
 */
export type DerivedDestroyRequest = {
  derived_resource_ids: Array<string>;
  invalidate?: boolean | undefined;
};

export const DerivedDestroyRequest$zodSchema: z.ZodType<
  DerivedDestroyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  derived_resource_ids: z.array(z.string()),
  invalidate: z.boolean().optional(),
}).describe("Request parameters for deleting derived resources");
