/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DestroyRequest = {
  api_key?: string | undefined;
  timestamp?: number | undefined;
  signature?: string | undefined;
  asset_id: string;
  invalidate?: boolean | undefined;
  notification_url?: string | undefined;
  callback?: string | undefined;
};

export const DestroyRequest$zodSchema: z.ZodType<
  DestroyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  api_key: z.string().optional(),
  asset_id: z.string(),
  callback: z.string().optional(),
  invalidate: z.boolean().optional(),
  notification_url: z.string().optional(),
  signature: z.string().optional(),
  timestamp: z.number().int().optional(),
});
