/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DestroyResponse,
  DestroyResponse$zodSchema,
} from "./destroyresponse.js";

export type DestroyByAssetIdGlobals = { cloud_name?: string | undefined };

export const DestroyByAssetIdGlobals$zodSchema: z.ZodType<
  DestroyByAssetIdGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DestroyByAssetIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  destroy_response?: DestroyResponse | undefined;
  api_error?: ApiError | undefined;
};

export const DestroyByAssetIdResponse$zodSchema: z.ZodType<
  DestroyByAssetIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  destroy_response: DestroyResponse$zodSchema.optional(),
});
