/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The result of the deletion operation.
 */
export const Result$zodSchema = z.enum([
  "ok",
  "not found",
]).describe("The result of the deletion operation.");

export type Result = z.infer<typeof Result$zodSchema>;

export type DestroyResponse = {
  result: Result;
  asset_folder?: string | undefined;
};

export const DestroyResponse$zodSchema: z.ZodType<
  DestroyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_folder: z.string().optional(),
  result: Result$zodSchema,
});
