/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const Direction$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type Direction = z.infer<typeof Direction$zodSchema>;
