/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The extended storage type of the resource.
 */
export const ExtendedStorageType$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "fetch",
  "list",
  "facebook",
  "twitter",
  "gravatar",
  "youtube",
  "hulu",
  "vimeo",
  "animoto",
  "worldstarhiphop",
  "dailymotion",
]).describe("The extended storage type of the resource.");

export type ExtendedStorageType = z.infer<typeof ExtendedStorageType$zodSchema>;
