/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const FieldsSpec$zodSchema = z.enum([
  "asset_folder",
  "folder",
  "filename",
  "format",
  "version",
  "version_id",
  "signature",
  "resource_type",
  "created_at",
  "uploaded_at",
  "bytes",
  "backup_bytes",
  "width",
  "height",
  "aspect_ratio",
  "access_control",
  "metadata",
  "context",
  "tags",
  "pixels",
  "custom",
  "moderation",
  "url",
  "secure_url",
  "status",
  "etag",
]);

export type FieldsSpec = z.infer<typeof FieldsSpec$zodSchema>;
