/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Folder, Folder$zodSchema } from "./folder.js";

export type FoldersSearchResponse = {
  total_count: number;
  time: number;
  next_cursor?: string | null | undefined;
  folders: Array<Folder>;
};

export const FoldersSearchResponse$zodSchema: z.ZodType<
  FoldersSearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  folders: z.array(Folder$zodSchema),
  next_cursor: z.string().nullable().optional(),
  time: z.number().int(),
  total_count: z.number().int(),
});
