/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Folder, Folder$zodSchema } from "./folder.js";

export type FoldersListResponse = {
  folders: Array<Folder>;
  next_cursor: string | null;
  total_count: number;
};

export const FoldersListResponse$zodSchema: z.ZodType<
  FoldersListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  folders: z.array(Folder$zodSchema),
  next_cursor: z.string().nullable(),
  total_count: z.number().int(),
});
