/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { UsageResponse, UsageResponse$zodSchema } from "./usageresponse.js";

export type GetUsageGlobals = { cloud_name?: string | undefined };

export const GetUsageGlobals$zodSchema: z.ZodType<
  GetUsageGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetUsageRequest = { date?: string | undefined };

export const GetUsageRequest$zodSchema: z.ZodType<
  GetUsageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: z.string().date().optional(),
});

export type GetUsageResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  usage_response?: UsageResponse | undefined;
  api_error?: ApiError | undefined;
};

export const GetUsageResponse$zodSchema: z.ZodType<
  GetUsageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  usage_response: UsageResponse$zodSchema.optional(),
});
