/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { FieldsSpec, FieldsSpec$zodSchema } from "./fieldsspec.js";
import { ListResponse, ListResponse$zodSchema } from "./listresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";

export type ListResourcesByAssetIDsGlobals = {
  cloud_name?: string | undefined;
};

export const ListResourcesByAssetIDsGlobals$zodSchema: z.ZodType<
  ListResourcesByAssetIDsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourcesByAssetIDsRequest = {
  asset_ids: Array<string>;
  resource_type?: ResourceType | undefined;
  fields?: Array<FieldsSpec> | undefined;
};

export const ListResourcesByAssetIDsRequest$zodSchema: z.ZodType<
  ListResourcesByAssetIDsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_ids: z.array(z.string()).describe(
    "List of asset IDs to retrieve (max 100).",
  ),
  fields: z.array(FieldsSpec$zodSchema).optional(),
  resource_type: ResourceType$zodSchema.optional(),
});

export type ListResourcesByAssetIDsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  list_response?: ListResponse | undefined;
  api_error?: ApiError | undefined;
};

export const ListResourcesByAssetIDsResponse$zodSchema: z.ZodType<
  ListResourcesByAssetIDsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  list_response: ListResponse$zodSchema.optional(),
});
