/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The delivery type for filtering resources in list operations.
 */
export const ListStorageType$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "fetch",
  "list",
]).describe("The delivery type for filtering resources in list operations.");

export type ListStorageType = z.infer<typeof ListStorageType$zodSchema>;
