/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { Direction, Direction$zodSchema } from "./direction.js";
import { FieldsSpec, FieldsSpec$zodSchema } from "./fieldsspec.js";
import { ListResponse, ListResponse$zodSchema } from "./listresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";

export type ListResourcesByAssetFolderGlobals = {
  cloud_name?: string | undefined;
};

export const ListResourcesByAssetFolderGlobals$zodSchema: z.ZodType<
  ListResourcesByAssetFolderGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourcesByAssetFolderRequest = {
  asset_folder: string;
  resource_type?: ResourceType | undefined;
  next_cursor?: string | undefined;
  max_results?: number | undefined;
  direction?: Direction | undefined;
  fields?: Array<FieldsSpec> | undefined;
};

export const ListResourcesByAssetFolderRequest$zodSchema: z.ZodType<
  ListResourcesByAssetFolderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_folder: z.string().describe("The full path of the asset folder."),
  direction: Direction$zodSchema.optional(),
  fields: z.array(FieldsSpec$zodSchema).optional(),
  max_results: z.number().int().describe(
    "Maximum number of results to return (1-500).",
  ).optional(),
  next_cursor: z.string().describe("Cursor for pagination.").optional(),
  resource_type: ResourceType$zodSchema.optional(),
});

export type ListResourcesByAssetFolderResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  list_response?: ListResponse | undefined;
  api_error?: ApiError | undefined;
};

export const ListResourcesByAssetFolderResponse$zodSchema: z.ZodType<
  ListResourcesByAssetFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  list_response: ListResponse$zodSchema.optional(),
});
