/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListResourceTypesGlobals = { cloud_name?: string | undefined };

export const ListResourceTypesGlobals$zodSchema: z.ZodType<
  ListResourceTypesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourceTypesRequest = {};

export const ListResourceTypesRequest$zodSchema: z.ZodType<
  ListResourceTypesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type ListResourceTypesError = { message: string };

export const ListResourceTypesError$zodSchema: z.ZodType<
  ListResourceTypesError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/**
 * Authentication failed.
 */
export type ListResourceTypesUnauthorizedResponseBody = {
  error: ListResourceTypesError;
};

export const ListResourceTypesUnauthorizedResponseBody$zodSchema: z.ZodType<
  ListResourceTypesUnauthorizedResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => ListResourceTypesError$zodSchema),
}).describe("Authentication failed.");

export const ListResourceTypesResourceType$zodSchema = z.enum([
  "image",
  "raw",
  "video",
]);

export type ListResourceTypesResourceType = z.infer<
  typeof ListResourceTypesResourceType$zodSchema
>;

/**
 * The list of resource types.
 */
export type ListResourceTypesResponseBody = {
  resource_types?: Array<ListResourceTypesResourceType> | undefined;
};

export const ListResourceTypesResponseBody$zodSchema: z.ZodType<
  ListResourceTypesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_types: z.array(ListResourceTypesResourceType$zodSchema).optional(),
}).describe("The list of resource types.");

export type ListResourceTypesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: ListResourceTypesResponseBody | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ListResourceTypesUnauthorizedResponseBody
    | undefined;
};

export const ListResourceTypesResponse$zodSchema: z.ZodType<
  ListResourceTypesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    ListResourceTypesUnauthorizedResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    ListResourceTypesResponseBody$zodSchema
  ).optional(),
});
