/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FoldersListResponse,
  FoldersListResponse$zodSchema,
} from "./folderslistresponse.js";

export type ListRootFoldersGlobals = { cloud_name?: string | undefined };

export const ListRootFoldersGlobals$zodSchema: z.ZodType<
  ListRootFoldersGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListRootFoldersRequest = {};

export const ListRootFoldersRequest$zodSchema: z.ZodType<
  ListRootFoldersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type ListRootFoldersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  folders_list_response?: FoldersListResponse | undefined;
  api_error?: ApiError | undefined;
};

export const ListRootFoldersResponse$zodSchema: z.ZodType<
  ListRootFoldersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  folders_list_response: FoldersListResponse$zodSchema.optional(),
});
