/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { Direction, Direction$zodSchema } from "./direction.js";
import { FieldsSpec, FieldsSpec$zodSchema } from "./fieldsspec.js";
import { ListResponse, ListResponse$zodSchema } from "./listresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";

export type ListResourcesByContextGlobals = { cloud_name?: string | undefined };

export const ListResourcesByContextGlobals$zodSchema: z.ZodType<
  ListResourcesByContextGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourcesByContextRequest = {
  resource_type: ResourceType;
  key: string;
  value?: string | undefined;
  next_cursor?: string | undefined;
  max_results?: number | undefined;
  direction?: Direction | undefined;
  fields?: Array<FieldsSpec> | undefined;
};

export const ListResourcesByContextRequest$zodSchema: z.ZodType<
  ListResourcesByContextRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  direction: Direction$zodSchema.optional(),
  fields: z.array(FieldsSpec$zodSchema).optional(),
  key: z.string().describe("Context key to filter by."),
  max_results: z.number().int().describe(
    "Maximum number of results to return (1-500).",
  ).optional(),
  next_cursor: z.string().describe("Cursor for pagination.").optional(),
  resource_type: ResourceType$zodSchema,
  value: z.string().describe("Context value to filter by.").optional(),
});

export type ListResourcesByContextResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  list_response?: ListResponse | undefined;
  api_error?: ApiError | undefined;
};

export const ListResourcesByContextResponse$zodSchema: z.ZodType<
  ListResourcesByContextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  list_response: ListResponse$zodSchema.optional(),
});
