/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { StorageType, StorageType$zodSchema } from "./storagetype.js";

/**
 * Status information returned for in-progress chunked uploads.
 *
 * @remarks
 * Note that fields that are not yet determined or not known at the time of the call are omitted from the response.
 */
export type NonFinalChunkUploadResponse = {
  done: boolean;
  bytes: number;
  kind?: StorageType | undefined;
  resource_type?: string | undefined;
  public_id?: string | undefined;
};

export const NonFinalChunkUploadResponse$zodSchema: z.ZodType<
  NonFinalChunkUploadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  bytes: z.number().int(),
  done: z.boolean(),
  kind: StorageType$zodSchema.optional(),
  public_id: z.string().optional(),
  resource_type: z.string().optional(),
}).describe(
  "Status information returned for in-progress chunked uploads.\n"
    + "Note that fields that are not yet determined or not known at the time of the call are omitted from the response.\n"
    + "",
);
