/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of resource.
 */
export const ResourceType$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe("The type of resource.");

export type ResourceType = z.infer<typeof ResourceType$zodSchema>;
