/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  RestoreResponseUnion,
  RestoreResponseUnion$zodSchema,
} from "./restoreresponseunion.js";

export type RestoreResourcesByAssetIDsGlobals = {
  cloud_name?: string | undefined;
};

export const RestoreResourcesByAssetIDsGlobals$zodSchema: z.ZodType<
  RestoreResourcesByAssetIDsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type RestoreResourcesByAssetIDsRequest = {
  asset_ids: Array<string>;
  versions?: Array<string> | undefined;
  notification_url?: string | undefined;
};

export const RestoreResourcesByAssetIDsRequest$zodSchema: z.ZodType<
  RestoreResourcesByAssetIDsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_ids: z.array(z.string()),
  notification_url: z.string().optional(),
  versions: z.array(z.string()).optional(),
});

export type RestoreResourcesByAssetIDsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  restore_response?: { [k: string]: RestoreResponseUnion } | undefined;
  api_error?: ApiError | undefined;
};

export const RestoreResourcesByAssetIDsResponse$zodSchema: z.ZodType<
  RestoreResourcesByAssetIDsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  restore_response: z.record(RestoreResponseUnion$zodSchema).describe(
    "Resources restored successfully",
  ).optional(),
});
