/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export type Security = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const Security$zodSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
  .object({
    cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
    oauth2: z.string().optional(),
  });
