/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FoldersListResponse,
  FoldersListResponse$zodSchema,
} from "./folderslistresponse.js";

export type ShowFolderGlobals = { cloud_name?: string | undefined };

export const ShowFolderGlobals$zodSchema: z.ZodType<
  ShowFolderGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ShowFolderRequest = { folder: string };

export const ShowFolderRequest$zodSchema: z.ZodType<
  ShowFolderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder: z.string(),
});

export type ShowFolderResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  folders_list_response?: FoldersListResponse | undefined;
  api_error?: ApiError | undefined;
};

export const ShowFolderResponse$zodSchema: z.ZodType<
  ShowFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  folders_list_response: FoldersListResponse$zodSchema.optional(),
});
