/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The storage type of the resource.
 */
export const StorageType$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
]).describe("The storage type of the resource.");

export type StorageType = z.infer<typeof StorageType$zodSchema>;
