/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type UpdateFolderGlobals = { cloud_name?: string | undefined };

export const UpdateFolderGlobals$zodSchema: z.ZodType<
  UpdateFolderGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateFolderRequestBody = { to_folder: string };

export const UpdateFolderRequestBody$zodSchema: z.ZodType<
  UpdateFolderRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  to_folder: z.string(),
});

export type UpdateFolderRequest = {
  folder: string;
  RequestBody: UpdateFolderRequestBody;
};

export const UpdateFolderRequest$zodSchema: z.ZodType<
  UpdateFolderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() => UpdateFolderRequestBody$zodSchema),
  folder: z.string(),
});

export type From = { name: string; path: string };

export const From$zodSchema: z.ZodType<From, z.ZodTypeDef, unknown> = z.object({
  name: z.string(),
  path: z.string(),
});

export type To = { name: string; path: string };

export const To$zodSchema: z.ZodType<To, z.ZodTypeDef, unknown> = z.object({
  name: z.string(),
  path: z.string(),
});

/**
 * Folder renamed successfully
 */
export type UpdateFolderResponseBody = { from: From; to: To };

export const UpdateFolderResponseBody$zodSchema: z.ZodType<
  UpdateFolderResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.lazy(() => From$zodSchema),
  to: z.lazy(() => To$zodSchema),
}).describe("Folder renamed successfully");

export type UpdateFolderResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: UpdateFolderResponseBody | undefined;
  api_error?: ApiError | undefined;
};

export const UpdateFolderResponse$zodSchema: z.ZodType<
  UpdateFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  object: z.lazy(() => UpdateFolderResponseBody$zodSchema).optional(),
});
