/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ExtendedStorageType,
  ExtendedStorageType$zodSchema,
} from "./extendedstoragetype.js";
import { Info, Info$zodSchema } from "./info.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  ResourceUpdateRequest,
  ResourceUpdateRequest$zodSchema,
} from "./resourceupdaterequest.js";

export type UpdateResourceByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const UpdateResourceByPublicIdGlobals$zodSchema: z.ZodType<
  UpdateResourceByPublicIdGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateResourceByPublicIdRequest = {
  resource_type: ResourceType;
  type: ExtendedStorageType;
  public_id: string;
  ResourceUpdateRequest: ResourceUpdateRequest;
};

export const UpdateResourceByPublicIdRequest$zodSchema: z.ZodType<
  UpdateResourceByPublicIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ResourceUpdateRequest: ResourceUpdateRequest$zodSchema,
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema,
  type: ExtendedStorageType$zodSchema,
});

export type UpdateResourceByPublicIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  info?: Info | undefined;
  api_error?: ApiError | undefined;
};

export const UpdateResourceByPublicIdResponse$zodSchema: z.ZodType<
  UpdateResourceByPublicIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  info: Info$zodSchema.optional(),
});
