/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { Info, Info$zodSchema } from "./info.js";
import {
  ResourceUpdateRequest,
  ResourceUpdateRequest$zodSchema,
} from "./resourceupdaterequest.js";

export type UpdateResourceByAssetIdGlobals = {
  cloud_name?: string | undefined;
};

export const UpdateResourceByAssetIdGlobals$zodSchema: z.ZodType<
  UpdateResourceByAssetIdGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateResourceByAssetIdRequest = {
  asset_id: string;
  ResourceUpdateRequest: ResourceUpdateRequest;
};

export const UpdateResourceByAssetIdRequest$zodSchema: z.ZodType<
  UpdateResourceByAssetIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ResourceUpdateRequest: ResourceUpdateRequest$zodSchema,
  asset_id: z.string().describe(
    "The asset ID of the resource. Must be a 32-character hexadecimal string.",
  ),
});

export type UpdateResourceByAssetIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  info?: Info | undefined;
  api_error?: ApiError | undefined;
};

export const UpdateResourceByAssetIdResponse$zodSchema: z.ZodType<
  UpdateResourceByAssetIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  info: Info$zodSchema.optional(),
});
