/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AsyncUploadResponse,
  AsyncUploadResponse$zodSchema,
} from "./asyncuploadresponse.js";
import { UploadRequest, UploadRequest$zodSchema } from "./uploadrequest.js";
import {
  UploadResourceType,
  UploadResourceType$zodSchema,
} from "./uploadresourcetype.js";
import { UploadResponse, UploadResponse$zodSchema } from "./uploadresponse.js";

export type UploadGlobals = { cloud_name?: string | undefined };

export const UploadGlobals$zodSchema: z.ZodType<
  UploadGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UploadRequestRequest = {
  resource_type?: UploadResourceType | undefined;
  upload_request: UploadRequest;
};

export const UploadRequestRequest$zodSchema: z.ZodType<
  UploadRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: UploadResourceType$zodSchema.default("auto"),
  upload_request: UploadRequest$zodSchema,
});

/**
 * Successful upload
 */
export type UploadResponseBody = AsyncUploadResponse | UploadResponse;

export const UploadResponseBody$zodSchema: z.ZodType<
  UploadResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  AsyncUploadResponse$zodSchema,
  UploadResponse$zodSchema,
]).describe("Successful upload");

export type UploadResponseResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  oneOf?: AsyncUploadResponse | UploadResponse | undefined;
  html_redirect?: string | undefined;
  api_error?: ApiError | undefined;
};

export const UploadResponseResponse$zodSchema: z.ZodType<
  UploadResponseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  html_redirect: z.string().describe(
    "Redirect to callback URL (when 'callback' parameter is provided and request is not XHR).",
  ).optional(),
  oneOf: z.union([
    AsyncUploadResponse$zodSchema,
    UploadResponse$zodSchema,
  ]).optional(),
});
