/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AsyncUploadResponse,
  AsyncUploadResponse$zodSchema,
} from "./asyncuploadresponse.js";
import { UploadResponse, UploadResponse$zodSchema } from "./uploadresponse.js";

export type UploadNoResourceTypeGlobals = { cloud_name?: string | undefined };

export const UploadNoResourceTypeGlobals$zodSchema: z.ZodType<
  UploadNoResourceTypeGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * Successful upload
 */
export type UploadNoResourceTypeResponseBody =
  | AsyncUploadResponse
  | UploadResponse;

export const UploadNoResourceTypeResponseBody$zodSchema: z.ZodType<
  UploadNoResourceTypeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  AsyncUploadResponse$zodSchema,
  UploadResponse$zodSchema,
]).describe("Successful upload");

export type UploadNoResourceTypeResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  oneOf?: AsyncUploadResponse | UploadResponse | undefined;
  html_redirect?: string | undefined;
  api_error?: ApiError | undefined;
};

export const UploadNoResourceTypeResponse$zodSchema: z.ZodType<
  UploadNoResourceTypeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  html_redirect: z.string().describe(
    "Redirect to callback URL (when 'callback' parameter is provided and request is not XHR).",
  ).optional(),
  oneOf: z.union([
    AsyncUploadResponse$zodSchema,
    UploadResponse$zodSchema,
  ]).optional(),
});
