/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { SearchResponse, SearchResponse$zodSchema } from "./searchresponse.js";

export type VisualSearchAssetsGlobals = { cloud_name?: string | undefined };

export const VisualSearchAssetsGlobals$zodSchema: z.ZodType<
  VisualSearchAssetsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type VisualSearchAssetsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  search_response?: SearchResponse | undefined;
  api_error?: ApiError | undefined;
};

export const VisualSearchAssetsResponse$zodSchema: z.ZodType<
  VisualSearchAssetsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_error: ApiError$zodSchema.optional(),
  search_response: SearchResponse$zodSchema.optional(),
});
