/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VisualSearchParameters3 = {
  text: string;
  threshold?: number | undefined;
};

export const VisualSearchParameters3$zodSchema: z.ZodType<
  VisualSearchParameters3,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  threshold: z.number().optional(),
});

export type VisualSearchParameters2 = {
  image_asset_id: string;
  threshold?: number | undefined;
};

export const VisualSearchParameters2$zodSchema: z.ZodType<
  VisualSearchParameters2,
  z.ZodTypeDef,
  unknown
> = z.object({
  image_asset_id: z.string(),
  threshold: z.number().optional(),
});

export type VisualSearchParameters1 = {
  image_url: string;
  threshold?: number | undefined;
};

export const VisualSearchParameters1$zodSchema: z.ZodType<
  VisualSearchParameters1,
  z.ZodTypeDef,
  unknown
> = z.object({
  image_url: z.string(),
  threshold: z.number().optional(),
});

/**
 * Parameters for visual search operations
 */
export type VisualSearchParametersUnion =
  | VisualSearchParameters1
  | VisualSearchParameters2
  | VisualSearchParameters3;

export const VisualSearchParametersUnion$zodSchema: z.ZodType<
  VisualSearchParametersUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => VisualSearchParameters1$zodSchema),
  z.lazy(() => VisualSearchParameters2$zodSchema),
  z.lazy(() => VisualSearchParameters3$zodSchema),
]).describe("Parameters for visual search operations");
